routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
Too new for 5.5
Auth::routes([
    'register' => false,
]);
*/

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::middleware('auth')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::resource('/companies', 'CompanyController');
    Route::resource('/employees', 'EmployeeController');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Company.php
<?php

namespace App;

use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Company extends Model
{
    protected $fillable = ['name', 'email', 'logo', 'website'];

    /**
     * @return HasMany
     */
    public function employees()
    {
        return $this->hasMany(Employee::class);
    }

    /**
     * @return string
     */
    public function getDisplayNameAttribute()
    {
        return $this->name;
    }

    /**
     * @return string
     */
    public function getLogoUrlAttribute()
    {
        if (!$this->logo) {
            return 'https://via.placeholder.com/100';
        }

        if (Str::contains($this->logo, 'http')) {
            return $this->logo;
        }

        return Storage::disk('logos')->url($this->logo);
    }

    /**
     * @return string
     */
    public function getWebsiteUrlAttribute()
    {
        if (Str::contains($this->website, 'http')) {
            return $this->website;
        }

        if (empty($this->website)) {
            return null;
        }

        return 'https://' . $this->website;
    }

    public function setLogoAttribute($value)
    {
        if ($value && method_exists($value, 'store')) {
            $path = $value->store(null, 'logos');
        } else {
            $path = $value;
        }

        $this->attributes['logo'] = $path;

        return $path;
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Exception;
use App\Company;
use Illuminate\Http\Response;
use App\Http\Requests\CompanyRequest as Request;

class CompanyController extends Controller
{
    const ITEMS_PER_PAGE = 10;

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $items = Company::withCount('employees')
            ->orderBy('updated_at', 'desc')
            ->paginate(self::ITEMS_PER_PAGE);

        return view('companies.index')->with([
            'items' => $items,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        $company = new Company;

        $data = $request->only($company->fillable);

        $company->fill($data);
        $company->save();

        session()->flash('message', $company->display_name . ' has been created.');

        return redirect()->route('companies.show', $company);
    }

    /**
     * Display the specified resource.
     *
     * @param Company $company
     * @return Response
     */
    public function show(Company $company)
    {
        $company->load('employees');

        return view('companies.show')->with([
            'item' => $company,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Company $company
     * @return Response
     */
    public function edit(Company $company)
    {
        return view('companies.edit')->with([
            'item' => $company,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Company $company
     * @return Response
     */
    public function update(Request $request, Company $company)
    {
        $data = $request->only($company->fillable);

        $company->update($data);

        session()->flash('message', $company->name . ' has been updated');

        return $this->edit($company);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Company $company
     * @return Response
     * @throws Exception
     */
    public function destroy(Company $company)
    {
        session()->flash('message', $company->display_name . ' has been deleted - sorry no confirmations today.');

        $company->delete();

        return redirect()->route('companies.index');
    }
}

resources/views/companies/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/companies">Companies</a></li>
            <li class="breadcrumb-item active" aria-current="page">Add new company</li>
        </ol>
    </nav>

    <div class="row justify-content-center">
        <div class="col-md-12">

            @if ($message = session('message'))
                <div class="alert alert-success">{{ $message }}</div>
            @endif

            @if($errors->isNotEmpty())
                <div class="alert alert-danger">Sorry a validation error occurred, please fix the errors below.</div>
            @endif

            <div class="card">
                <div class="card-header">Adding a new company</div>

                <div class="card-body">

                    <div class="form-area mt-4">

                        <form name="edit-form" method="POST" action="{{ route('companies.store') }}" enctype="multipart/form-data">

                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="name">Company name (required)</label>
                                <input class="form-control" id="name" name="name" value="{{ old('name') }}" >
                                @if($errors->has('name'))
                                    <div class="mt-1 alert alert-danger validation-error" role="alert">{{ $errors->first('name') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" class="form-control" id="email" name="email" value="{{ old('email') }}" >
                            </div>

                            <div class="form-group">
                                <label for="website">Company website</label>
                                <input type="url" class="form-control" id="website" name="website" value="{{ old('website') }}" >
                            </div>

                            <div class="form-group">
                                <label for="logo">Company logo</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input accept="image/*" type="file" class="custom-file-input" name="logo" id="logo">
                                        <label class="custom-file-label" for="logo">Choose file</label>
                                    </div>
                                </div>
                                @if($errors->has('logo'))
                                    <div class="mt-1 alert alert-danger validation-error" role="alert">{{ $errors->first('logo') }}</div>
                                @endif
                            </div>

                            <button type="submit" class="btn btn-primary">Create company</button>

                        </form>

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/companies/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/companies">Companies</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ $item->display_name }}</li>
        </ol>
    </nav>

    <div class="row justify-content-center">
        <div class="col-md-12">

            @if ($message = session('message'))
                <div class="alert alert-success">{{ $message }}</div>
            @endif

            @if($errors->isNotEmpty())
                <div class="alert alert-danger">Sorry a validation error occurred, please fix the errors below.</div>
            @endif

            <div class="card">
                <div class="card-header">Editing... {{ $item->display_name }}</div>

                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <div class="position-relative">
                            <img style="width: 100px; height: auto;" class="rounded img-thumbnail" src="{{ $item->logo_url }}" alt="Logo for {{ $item->name }}">
                            <button onClick="alert('Coming soon.')" class="position-absolute btn btn-sm" style="bottom: 4px; right: -3px;">🗑</button>
                        </div>
                        <div class="p-3">
                            <strong>Email:</strong> <a href="mailto:{{ $item->email }}">{{ $item->email }}</a><br/>
                            <strong>Website:</strong> <a href="{{ $item->website_url }}" rel="noopener">{{ $item->website }}</a><br/>
                            <strong>Employee Count:</strong> {{ $item->employees->count() }}
                        </div>
                        <div>
                            <div class="btn-group">
                                <form name="delete-form" action="{{ route('companies.destroy', $item) }}" method="POST">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="DELETE">
                                    <button type="submit" class="btn btn-sm btn-outline-danger">Delete</button>
                                </form>
                            </div>
                        </div>
                    </div>

                    <div class="form-area mt-4">

                        <form name="edit-form" method="POST" action="{{ route('companies.update', $item) }}" enctype="multipart/form-data">

                            {{ csrf_field() }}

                            <input type="hidden" name="_method" value="PUT">

                            <div class="form-group">
                                <label for="name">Company name (required)</label>
                                <input class="form-control" id="name" name="name" value="{{ old('name', $item->name) }}" >
                                @if($errors->has('name'))
                                    <div class="mt-1 alert alert-danger validation-error" role="alert">{{ $errors->first('name') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" class="form-control" id="email" name="email" value="{{ old('email', $item->email) }}" >
                            </div>

                            <div class="form-group">
                                <label for="website">Company website</label>
                                <input type="url" class="form-control" id="website" name="website" value="{{ old('website', $item->website_url) }}" >
                            </div>

                            <div class="form-group">
                                <label for="logo">Company logo</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input accept="image/*" type="file" class="custom-file-input" name="logo" id="logo">
                                        <label class="custom-file-label" for="logo">Choose file</label>
                                    </div>
                                </div>
                                @if($errors->has('logo'))
                                    <div class="mt-1 alert alert-danger validation-error" role="alert">{{ $errors->first('logo') }}</div>
                                @endif
                            </div>

                            <button type="submit" class="btn btn-primary">Save changes</button>

                        </form>

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/companies/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/companies">Companies</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ $item->display_name }}</li>
        </ol>
    </nav>

    <div class="row justify-content-center">

        <div class="col-md-12">

            @if ($message = session('message'))
                <div class="alert alert-success">{{ $message }}</div>
            @endif

            <div class="card">
                <div class="card-header">{{ $item->display_name }}</div>

                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <div class="position-relative">
                            <img style="width: 100px; height: auto;" class="rounded img-thumbnail" src="{{ $item->logo_url }}" alt="Logo for {{ $item->name }}">
                            <button onClick="alert('Coming soon.')" class="position-absolute btn btn-sm" style="bottom: 4px; right: -3px;">🗑</button>
                        </div>
                        <div class="p-3">
                            <strong>Email:</strong> <a href="mailto:{{ $item->email }}">{{ $item->email }}</a><br/>
                            <strong>Website:</strong> <a href="{{ $item->website_url }}" rel="noopener">{{ $item->website }}</a><br/>
                            <strong>Employee Count:</strong> {{ $item->employees->count() }}
                        </div>
                        <div>
                            <form name="delete-form" action="{{ route('companies.destroy', $item) }}" method="POST">
                                {{ csrf_field() }}
                                <input type="hidden" name="_method" value="DELETE">
                                <div class="btn-group">
                                    <a href="{{ route('employees.create', ['company_id' => $item->id]) }}" class="btn btn-sm btn-outline-success">Add employee</a>
                                    <a href="{{ route('companies.edit', $item) }}" class="btn btn-sm btn-outline-info">Edit</a>
                                    <button type="submit" class="btn btn-sm btn-outline-danger">Delete</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <h2>Employees</h2>
                </div>

                @if($item->employees->isEmpty())
                    <div class="card-body">
                        <div class="alert alert-info text-center">
                            <p>You should try employing somebody, it's a right hoot.</p>
                            <p class="mb-0"><a class="btn btn-sm btn-outline-success" href="{{ route('employees.create', ['company_id' => $item->id]) }}">Add employee</a></p>
                        </div>
                    </div>
                    @else
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>Actions</th>
                        </tr>
                        </thead>

                        <tbody>
                        @foreach($item->employees as $employee)
                            <tr>
                                <td><a href="{{ route('employees.show', $employee) }}">{{ $employee->display_name }}</a></td>
                                <td><a href="mailto:{{ $employee->email }}">{{ $employee->email }}</a></td>
                                <td><a href="tel:{{ $employee->phone }}">{{ $employee->phone }}</a></td>
                                <td class="text-right">
                                    {{-- I know this is naughty - but for demo purposes. --}}
                                    <form name="delete-form" action="{{ route('employees.destroy', $item) }}" method="POST">
                                        {{ csrf_field() }}
                                        <input type="hidden" name="_method" value="DELETE">
                                        <div class="btn-group">
                                            <a href="{{ route('employees.edit', $item) }}" class="btn btn-sm btn-outline-info">Edit</a>
                                            <button type="submit" class="btn btn-sm btn-outline-danger">Delete</button>
                                        </div>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>

                    </table>
                @endif

            </div>
        </div>
    </div>
</div>
@endsection