routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
Too new for 5.5
Auth::routes([
    'register' => false,
]);
*/

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::middleware('auth')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::resource('/companies', 'CompanyController');
    Route::resource('/employees', 'EmployeeController');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Employee extends Model
{
    protected $fillable = ['first_name', 'last_name', 'email', 'phone', 'company_id'];

    /**
     * @return BelongsTo
     */
    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    /**
     * @return string
     */
    public function getDisplayNameAttribute()
    {
        $parts = [$this->first_name, $this->last_name];
        $parts = array_filter($parts);

        return implode(' ', $parts);
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Exception;
use App\Company;
use App\Employee;
use Illuminate\Http\Response;
use App\Http\Requests\EmployeeRequest as Request;

class EmployeeController extends Controller
{
    const ITEMS_PER_PAGE = 10;

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $items = Employee::with('company')
            ->has('company')
            ->orderBy('company_id')
            ->paginate(self::ITEMS_PER_PAGE);

        return view('employees.index')->with([
            'company_count' => Company::count(),
            'items' => $items,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('employees.create')->with([
            'companies' => Company::all()->sortBy('name'),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        $employee = new Employee;

        $data = $request->only($employee->fillable);

        $employee->fill($data);
        $employee->save();

        session()->flash('message', $employee->display_name . ' has been created.');

        return redirect()->route('employees.show', $employee);
    }

    /**
     * Display the specified resource.
     *
     * @param Employee $employee
     * @return Response
     */
    public function show(Employee $employee)
    {
        $employee->load('company');

        return view('employees.show')->with([
            'item' => $employee,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Employee $employee
     * @return Response
     */
    public function edit(Employee $employee)
    {
        return view('employees.edit')->with([
            'item' => $employee,
            'companies' => Company::all()->sortBy('name'),
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Request $request
     * @param Employee $employee
     * @return Response
     */
    public function update(Request $request, Employee $employee)
    {
        $data = $request->only($employee->fillable);

        $employee->update($data);

        session()->flash('message', $employee->display_name . ' has been updated');

        return $this->edit($employee);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Employee $employee
     * @return Response
     * @throws Exception
     */
    public function destroy(Employee $employee)
    {
        session()->flash('message', $employee->display_name . ' has been deleted - sorry no confirmations today.');

        $employee->delete();

        return redirect()->route('employees.index');
    }
}

resources/views/employees/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/employees">Employees</a></li>
            <li class="breadcrumb-item active" aria-current="page">Add new employee</li>
        </ol>
    </nav>

    <div class="row justify-content-center">
        <div class="col-md-12">

            @if ($message = session('message'))
                <div class="alert alert-success">{{ $message }}</div>
            @endif

            @if($errors->isNotEmpty())
                <div class="alert alert-danger">Sorry a validation error occurred, please fix the errors below.</div>
            @endif

            <div class="card">
                <div class="card-header">Adding a new employee</div>

                <div class="card-body">

                    <div class="form-area mt-4">

                        <form name="edit-form" method="POST" action="{{ route('employees.store') }}">

                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="name">First name (required)</label>
                                <input class="form-control" id="first_name" name="first_name" value="{{ old('first_name') }}" >
                                @if($errors->has('first_name'))
                                <div class="mt-1 alert alert-danger validation-error" role="alert">{{ $errors->first('first_name') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="name">Last name (required)</label>
                                <input class="form-control" id="last_name" name="last_name" value="{{ old('last_name') }}" >
                                @if($errors->has('last_name'))
                                <div class="mt-1 alert alert-danger validation-error" role="alert">{{ $errors->first('last_name') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" class="form-control" id="email" name="email" value="{{ old('email') }}" >
                            </div>

                            <div class="form-group">
                                <label for="phone">Phone</label>
                                <input type="tel" class="form-control" id="phone" name="phone" value="{{ old('phone') }}" >
                            </div>

                            <div class="form-group">
                                @php $company_id = (int) old('company_id', request()->get('company_id')) @endphp
                                <label for="company_id">Company (required)</label>
                                <select class="form-control" name="company_id" id="company_id">
                                    <option value="" disabled {{ $company_id ? '' : 'selected' }}>-- Please Select</option>
                                    @foreach($companies as $company)
                                        <option {{ $company_id === $company->id ? 'selected' : '' }} value="{{ $company->id }}">{{ $company->display_name }}</option>
                                    @endforeach()
                                </select>
                                @if($errors->has('company_id'))
                                    <div class="mt-1 alert alert-danger validation-error" role="alert">{{ $errors->first('company_id') }}</div>
                                @endif
                            </div>

                            <button type="submit" class="btn btn-primary">Create employee</button>

                        </form>

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/employees/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="/employees">Employees</a></li>
                <li class="breadcrumb-item active" aria-current="page">Editing {{ $item->display_name }}</li>
            </ol>
        </nav>

        <div class="row justify-content-center">
            <div class="col-md-12">

                @if ($message = session('message'))
                    <div class="alert alert-success">{{ $message }}</div>
                @endif

                @if($errors->isNotEmpty())
                    <div class="alert alert-danger">Sorry a validation error occurred, please fix the errors below.</div>
                @endif

                <div class="card">
                    <div class="card-header">Adding a new employee</div>

                    <div class="card-body">

                        <div class="form-area mt-4">

                            <form name="edit-form" method="POST" action="{{ route('employees.update', $item) }}">

                                {{ csrf_field() }}

                                <input type="hidden" name="_method" value="PUT">

                                <div class="form-group">
                                    <label for="name">First name (required)</label>
                                    <input class="form-control" id="first_name" name="first_name" value="{{ old('first_name', $item->first_name) }}" >
                                    @if($errors->has('first_name'))
                                        <div class="mt-1 alert alert-danger validation-error" role="alert">{{ $errors->first('first_name') }}</div>
                                    @endif
                                </div>

                                <div class="form-group">
                                    <label for="name">Last name (required)</label>
                                    <input class="form-control" id="last_name" name="last_name" value="{{ old('last_name', $item->last_name) }}" >
                                    @if($errors->has('last_name'))
                                        <div class="mt-1 alert alert-danger validation-error" role="alert">{{ $errors->first('last_name') }}</div>
                                    @endif
                                </div>

                                <div class="form-group">
                                    <label for="email">Email</label>
                                    <input type="email" class="form-control" id="email" name="email" value="{{ old('email', $item->email) }}" >
                                </div>

                                <div class="form-group">
                                    <label for="phone">Phone</label>
                                    <input type="tel" class="form-control" id="phone" name="phone" value="{{ old('phone', $item->phone) }}" >
                                </div>

                                <div class="form-group">
                                    <label for="company_id">Company (required)</label>
                                    <select class="form-control" name="company_id" id="company_id">
                                        <option value="" disabled>-- Please Select</option>
                                        @foreach($companies as $company)
                                            <option {{ old('company_id', $item->company_id) === $company->id ? 'selected' : '' }} value="{{ $company->id }}">{{ $company->display_name }}</option>
                                        @endforeach()
                                    </select>
                                    @if($errors->has('company_id'))
                                        <div class="mt-1 alert alert-danger validation-error" role="alert">{{ $errors->first('company_id') }}</div>
                                    @endif
                                </div>

                                <button type="submit" class="btn btn-primary">Save changes</button>

                            </form>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/employees/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/employees">Employees</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ $item->display_name }}</li>
        </ol>
    </nav>

    <div class="row justify-content-center">

        <div class="col-md-12">

            @if ($message = session('message'))
                <div class="alert alert-success">{{ $message }}</div>
            @endif

            <div class="card">
                <div class="card-header">{{ $item->display_name }}</div>

                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <div class="p-3">
                            <strong>Email:</strong> <a href="mailto:{{ $item->email }}">{{ $item->email }}</a><br/>
                            <strong>Phone:</strong> <a href="tel:{{ $item->phone }}">{{ $item->phone }}</a><br/>
                            <strong>Company:</strong> <a href="{{ route('companies.show', $item->company) }}">{{ $item->company->display_name }}</a>
                        </div>
                        <div>
                            <form name="delete-form" action="{{ route('employees.destroy', $item) }}" method="POST">
                                {{ csrf_field() }}
                                <input type="hidden" name="_method" value="DELETE">
                                <div class="btn-group">
                                    <a href="{{ route('employees.edit', $item) }}" class="btn btn-sm btn-outline-info">Edit</a>
                                    <button type="submit" class="btn btn-sm btn-outline-danger">Delete</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
@endsection